---
title: "Computing Progress Report"
author: "Zachary Johns, Emma Berry, Christian Wright, and Garrett Elmore"
date: "4/15/2020"
output: html_document
---

## Computing Progress Report

Our group is using an EZO pH meter to detect the pH during two titrations between amino acids L-arginine and L-lysine. The EZO pH meter will be hooked up to a raspberry pi or directly to a laptop so the data points for the titration will be stored. The i2c method or UART will be used, respectively, if using the Raspberry pi or a computer.

Considering the heavy limitations we now have on our project due to the transition online, we are now solely focusing on the programming side and finding ways to write a program to help generate a titration curve and find an isoelectric point. With that being said, the designated tasks at the beginning of the semester have been modified. At this point in the progress of our project, all the members are currently finding which programming method (i2c or UART) will be most doable. Currently, programming methods for the i2c has been most successful after reading through the EZO ph meter guide and discovering useful coding ideas. Furthermore, with each member having access to a Raspberry Pi, this programming method wouldnt change the difficulty of matters. We plan to make a decision within the next few days after some more research. The UART method would be more convenient because it could be run on the laptops without the need for a Raspberry Pi, but as of right now, the resources we have found are pointing us in the opposite direction.

If the UART method is decided to be used, we will communicate with the Python serial module since the UART behaves like a serial port.

When a certain method has been established, most likely i2c, two members will focus on writing a code to generate a graph and the other two members will write a code to find the isoelectric point. At this point, these tasks seems suitable for two people to take on. However, if one tasks needs more assistance, the designated roles will be shifted to appropriatly assist as needed. 

Dr. Malmberg has already been a helpful resource in this project as well as the EZO pH meter manual. 

Codes that have already been discovered/wrtiten will be posted in the repository with a brief discription as to what the code is saying. These codes are for the Raspberry Pi (i2c method). 

I am currently looking at R files from class and looking at various examples online. I would assume we could use a function similar to the ones shown in the Rintro document but retrieving the data and having it save to the global enviornment in real-time is somthing I'm not quite sure about yet
