---
title: "Final Notebook"
author: "Emma Berry, Zach John, Garett Elmore, and Christian Wright"
date: "5/3/2020"
output: html_document
---

Emma's Part:
# The pH meter and the Raspberry Pi are connected.
The GND pin on the pH meter connects to the ground pin on the Raspberry Pi.
TX(SDA)pin on the pH meter connects to GPIO pin 2 on the Raspberry Pi
RX(SCL) on the pH connects to GPIO pin 3 on the Raspberry Pi.
The PRB and PGND pins connect to the board and the shield pins of BNC.

# Power
Connect the Vcc pin to the +3.3 V pin in order to generate power.

# Check to make sure the connection between the Raspberry Pi and pH meter is good.
```
i2cdetect - y 1
```

# Installing Required Python Modules
```
#!/usr/bin/env python
import io
import fctnl
import time
import string
```
the first is used to create file streams
the second is used to access the I2C parameters like addresses
the third is used for sleep delay and timestamps
the last one helps parse the strings

Zach's Part:

# Enable I2C modules on the Raspberry Pi.

```
sudo raspi-config
```

# Select interfacing options, select I2C, and then reboot the Raspberry Pie. 

```
sudo reboot
```

# Open the terminal and install up-to-date Raspbian packages.

```
sudo apt
sudo apt dist-upgrade
sudo apt autoremove
sudo apt clean
```

# Add Raspbian tools package

```
sudo apt install i2c-tools
i2cdetect -y 1
```

# A chart/graph will be generated, indicating the I2C module is working correcrtly. 

# Connect the pH sensor

# Get the pH circuit into the correct mode. The pH circuit is in UART (serial) mode.

# The breadbored will then be activated for the I2C modules.

# The power is cut and the PGND pin was shorted to the TX pin.

# The device is powered and the LED light changes from Green to Blue

# The short was removed from the probe pin to the TX pin

# The device was power cycled.

#Christian's part

```
class atlas_i2c:
    long_timeout = 1.5  
    short_timeout = .5
#Time needed to query readings
    default_bus = 1  
    default_address = 99
#Defines the bus
    def __init__(self, address=default_address, bus=default_bus):
    self.file_read = io.open("/dev/i2c-" + str(bus), "rb", buffering=0)
        self.file_write = io.open("/dev/i2c-" + str(bus), "wb", buffering=0)
#Allows the program to read and write binary
    self.set_i2c_address(address)
    def set_i2c_address(self, addr):
        I2C_SLAVE = 0x703
#The PH meter must be the slave
        fcntl.ioctl(self.file_read, I2C_SLAVE, addr)
        fcntl.ioctl(self.file_write, I2C_SLAVE, addr)
    def write(self, string):string += ""           
    self.file_write.write(bytes(string, 'UTF-8'))
def read(self, num_of_bytes=31):
#Defines the size of data interpreted at one time
        res = self.file_read.read(num_of_bytes)  
        response = list([x for x in res])
        if response[0] == 1:char_list = [chr(x & ~0x80) for x in list(response[1:])]
            return "Command succeeded " + ''.join(char_list)
        else:
            return "Error " + str(response[0])
    def query(self, string):self.write(string)
        if((string.upper().startswith("R")) or
           (string.upper().startswith("CAL"))):
            time.sleep(self.long_timeout)
 #Read and calibration commands need a longer timeout.
        elif((string.upper().startswith("SLEEP"))):
            return "sleep mode"
        else:
            time.sleep(self.short_timeout)
            return self.read()
        def close(self):
        self.file_read.close()
        self.file_write.close()
def main():
    device = atlas_i2c()  
    print(">> Atlas Scientific sample code")
    print(">> Any commands entered are passed to the board via" 
          "I2C except:")
    print(">> Address,xx changes the I2C address the Raspberry"
         " Pi communicates with.")
    print(">> Poll,xx.x command continuously polls the board"
          "every xx.x seconds")
    print(" where xx.x is longer than the {} second timeout.".
         format(atlas_i2c.long_timeout))
    print(" Pressing ctrl-c will stop the polling")
```
#Allows Raspberry Pi to interface with the PH circuit.

